project:
  type: website
  output-dir: docs    # <- add / change this line
  render: 
  - "*.qmd"

execute:
  echo: true
  python:
    version: "r-reticulate"
    
website:
  back-to-top-navigation: true
  page-navigation: true
  title: "HDS MSc - Module 3 - Supervised Learning - Classification - Logistic Reg"
  navbar:
    background: primary
    search: true
    left:
      - text: "Supervised Learning:Logistic Regression"
        file: LogisticRegression.qmd
 
  sidebar:
     - title: "Supervised Learning:Logistic Regression"
       contents:
         - tidymodels_sklearn_overview.qmd
         - logistic_regression_tidymodels.qmd
         - logistic_regression_python.qmd
         - decision_threshold.qmd
         #- Gradients.qmd
         #- LogisticRegression.qmd
  
  page-footer: 
    left: "Copyright 2025, Laura Bravo" 
    background: light


    
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
   # code-fold: true
    code-tools: true
    code-link: true

editor: visual

